### ISSUE TITLE
Saving Images byte array format instead of base64

### ISSUE THREAD

**Issue by mbaldassarri** [jhuckaby/webcamjs#107]
Hi everybody,
is it possible to take a picture saving directly a byte[] or an image jpg without converting it from base64 ?
Thanks a lot!

**Comment by jhuckaby** [comment]
Unfortunately, base64 is the only way to get the image out of Adobe Flash into JavaScript land, which is why that conversion is done.  However, you can get access to the underlying canvas yourself, if you want to grab pixels from that.  Instructions are here:

https://github.com/jhuckaby/webcamjs#snapping-a-picture
