### ISSUE TITLE
Chrome: Uncaught TypeError: navigator.mediaDevices.getUserMedia is not a function

### ISSUE THREAD

**Issue by stueynet** [jhuckaby/webcamjs#124]
Getting this in our app but also on all your demos. See screencap below. Chrome on Mac OS Version 47.0.2526.73 (64-bit)

http://d.pr/i/14Zk2

**Comment by jhuckaby** [comment]
Yikes, thank you for letting me know.  They did something weird in Chrome 47.  I'll get this fixed tonight.

**Comment by KirDE** [comment]
Thank you for very fast reply. We are using webcam.js in our intranet and it is very critical for us.

**Comment by rockbass2560** [comment]
Thanks for you effort jhuckaby. Chrome retired support for "getUserMedia" :(.

**Comment by positlabs** [comment]
Seems like `navigator.webkitGetUserMedia()` still works fine.

**Comment by jhuckaby** [comment]
Hey guys,

So ironically, I already [fixed this in the latest commit](https://github.com/jhuckaby/webcamjs/commit/394584d9cfbfde1c247baa9597fcfcbe7fc1d476), but I failed to update my demo site.  That's all fixed now, but there is a new problem.  Chrome 47 **requires that the site be HTTPS** in order for user media / webcam to work!  This is a brand new requirement that I didn't see coming...

<img width="562" alt="screenshot 2015-12-03 17 25 48" src="https://cloud.githubusercontent.com/assets/700765/11580475/a0d7abdc-99ec-11e5-9eee-5a3b7bb936e9.png">

Chromium Docs on the topic:
https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features

This means that all my hosted demos will fail, because I don't have HTTPS on my server yet.  I'll have to buy a SSL cert and update the docs and all my links.  But if you grab the [latest commit](https://github.com/jhuckaby/webcamjs/commit/394584d9cfbfde1c247baa9597fcfcbe7fc1d476) from GitHub, the library should work fine in Chrome 47, as long as you are using it on 127.0.0.1, or over HTTPS.

I'll tag v1.0.6 with this commit too, as soon as I get my HTTPS situation resolved.

Thanks for reporting this!

**Comment by rockbass2560** [comment]
I tested the library with https and it works fine. I have reviewed in different sites and this problem is in all websites. Sincerely, I don't understand this decision from Google.

**Comment by KirDE** [comment]
We have to buy now a certificate for local(!) Server. So stupid.

**Comment by jhuckaby** [comment]
You don't need HTTPS for localhost.  Check the [Chromium docs](https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features) for the whitelist:

'''
(https, *, *)
(wss, *, *)
(*, localhost, *)
(*, *.localhost, *)
(*, 127/8, *)
(*, ::1/128, *)
(file, *, —)
(chrome-extension, *, —) 
'''

**Comment by KirDE** [comment]
for local Network, not for same PC.

**Comment by positlabs** [comment]
This free SSL cert service might be worth a shot. http://www.theregister.co.uk/2015/12/03/letsencrypt_public_beta/?mt=1449248133223

Actually... looks like you got https working on your site.

Another solution would be to push demos to gh-pages branch, and have them hosted on github (which supports https).

**Comment by jhuckaby** [comment]
Yup, got it working late last night.  I just have to update all the links to the demos, put a huge disclaimer in the docs, and push out a v1.0.6 tag.

**Comment by jhuckaby** [comment]
Tagged v1.0.6 with support for `navigator.mediaDevices` in Firefox and Chrome, and updated all the demo links to be HTTPS.  Updated docs with very loud disclaimer about Chrome.

https://github.com/jhuckaby/webcamjs/releases/tag/v1.0.6

**Comment by stueynet** [comment]
Thanks @jhuckaby! 1.0.6 works with SSL on the server and just works locally as you said. Our production server already has SSL but if anyone is looking for free ssl for your development or staging servers you should try https://letsencrypt.org/.

**Comment by mmhaqco** [comment]
Webcam.js Error: Could not access webcam: NotAllowedError: Permission denied NotAllowedError: Permission denied

Google Chrome Version 92.0.4515.159 (Official Build) (64-bit)

any solution???
Thanks
