### ISSUE TITLE
Cross-domain in IE9?

### ISSUE THREAD

**Issue by ScottDellinger** [jhuckaby/webcamjs#125]
First, want to say I love the library. I'm using it in a project that allows the online proctoring of exams, etc. Unfortunately, about the same time that Google put in the requirement for Chrome 47 to be https (thanks for the quick update about that!), it seems that I can no longer even load the webcam in IE9 across different domains. Do you know of anything that may have happened? It gives me an "Access to camera denied" error.

No files were changed on the project. This just started happening all of a sudden.

I can provide you with username/password for the site to test, if you're willing. I've been at it for about two days straight and am no closer to getting it to work again.

**Comment by positlabs** [comment]
Honestly, I don't think it's worth trying to support IE9 any more. Microsoft is dropping support for it in Jan. 2016 (next month!). http://www.zdnet.com/article/microsoft-to-drop-support-for-older-versions-of-internet-explorer/

**Comment by jhuckaby** [comment]
Sorry to hear that, @ScottDellinger.  I will take a look as soon as I have time (I don't have an IE 9 machine with a webcam currently -- I honestly have already stopped testing for it).

What do you mean when you say "across different domains"?  Do you mean the `webcam.js` file is hosted on a different domain as your HTML page?   Can you try hosting it on the same domain and see if it works?  IE 9 doesn't even support user media, so it's actually Flash we're really dealing with here.  I wouldn't be a bit surprised if Flash needs to be hosted on the same domain as the page, in order to access the webcam, depending on your IE and/or Flash security settings (might try messing with those as well -- add your page as a "Trusted Zone" or something).

I agree with @positlabs, IE 9 is becoming unsupported rather soon.  Might want to think about upgrading to Edge!

**Comment by ScottDellinger** [comment]
Thanks folks... I just spoke with the CEO of the (very large) corporation using the service and managed to convince them to let me stop supporting lower than IE11 effective immediately.

Thanks again for the library, @jhuckaby! :)

**Comment by jhuckaby** [comment]
Glad to hear it!  Now if I could just convince MY company to drop IE 9, hahaha :)

**Comment by borisreitman** [comment]
IE9 won't be dropped until April 2017 because thats when Vista is dropped.

So, I propose to fix the upload of the snapshot on IE9 by using Flash to upload it, with URLLoader object.

**Comment by jhuckaby** [comment]
@borisreitman That would overcomplicate the library for a browser that currently has 2% market share and dropping.  No thanks.  Also, the end date of IE 9 support is officially January 12, 2016, and this comes direct from Microsoft.  Reference: https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support

**Comment by borisreitman** [comment]
Scott, I recommend to load the webcam.swf from the same domain as your website, do not use a subdomain. 

If your site runs on many domains use an iframe at the same domain as webcam.swf, and just control the iframe using postMessage interface. Since your viewport is probably a fixed size, you can hardcode the iframe to be that size, which removes most caveats with iframe integration.

If you don't want this, you may have to have a crossdomain.xml file or worse, to run a Flash policy daemon on port 843 service a similar xml file.  Also use Flash Player with debug enabled, you will see more errors. And you can enable tracing to flashlog.txt and you can see more info. If this is new to you, you will have to do some reading online.

**Comment by jhuckaby** [comment]
@borisreitman He resolved his issue already.
