### ISSUE TITLE
webcam not connected error case

### ISSUE THREAD

**Issue by borisreitman** [jhuckaby/webcamjs#130]
Is there a way to distinguish if webcam is present but not permitted to use, and the case in which there is no webcam connected to the computer (example: for a USB webcam) ?

**Comment by jhuckaby** [comment]
Yes, add an `error` event listener and examine the error message string passed to your callback function.  It will be one of the following:

```
Could not access webcam: PermissionDeniedError: 
Could not access webcam: PermissionDismissedError: 
Could not access webcam: DevicesNotFoundError: 
```

If the string contains `DevicesNotFoundError`, then the user has no camera.  Otherwise they denied access to the camera.

When the user is using a browser that doesn't support HTML5 getUserMedia, such as IE or Safari, and is running in Adobe Flash fallback mode, the error message will be different.  One of these:

```
Access to camera denied
No camera was detected.
```
