### ISSUE TITLE
in mirror mode flash permissions screen is flipped too

### ISSUE THREAD

**Issue by borisreitman** [jhuckaby/webcamjs#134]
A minor problem: If I right-click on Flash player movie, and select Settings, I get it flipped.

![flash_permissions_flipped](https://cloud.githubusercontent.com/assets/408599/12012286/c0812012-aca2-11e5-8812-304877911e10.png)

I am using the mirror mode (flip_horiz configuration option) because I want the camera to behave as it is in Skype.

I think it should be possible to fix this by transforming only the internal MovieClip, and not the whole flash player movie.

**Comment by jhuckaby** [comment]
Yeah, sorry, I'm doing the mirror flip in HTML5 CSS, not in Flash, so the entire movie DIV is getting flipped.  Someday I'll figure out how to do it properly and rewrite the mirror feature.

**Comment by positlabs** [comment]
It's a pain, but I think this issue can be fixed by reacting to events dispatched by the webcam. You simply need to un-mirror the div while the dialog is visible.

**Comment by jhuckaby** [comment]
To my knowledge, there is no way to catch the events of when the user manually goes to the settings dialog, and when he dismisses it.  I don't think Flash emits events for those things.

Luckily, this only happens when someone right-clicks in the Flash movie and selects "Settings".  It does not happen when I throw up the dialog on startup (I am delaying the mirror effect until after the user clicks Allow).  So I wouldn't call this a P1 bug.  But I think I can flip the internal camera object internally in Flash, and skip the CSS3 transform.  It's a bit messy, but doable.

**Comment by borisreitman** [comment]
Sorry, didn't mean to make this P1.

**Comment by osdiab** [comment]
I'd like to vote for this one as well—I'll investigate if I can figure out how to make this work.

**Comment by osdiab** [comment]
Implemented a fix—check it out :3

**Comment by borisreitman** [comment]
I looked at it, it looks nice and clean. Let see if the maintainer merges it in. Btw, you may check out my fork where I have added info how to build flash without actually having an ide, but just using the sdk.

**Comment by jhuckaby** [comment]
Oh wow!  @osdiab this is awesome!  Thank you so much!  I've been wanting to implement this forever, but I was terrified to touch the ActionScript.  It frightens me.  I'll review and accept this PR very soon!

@borisreitman Thanks for reviewing it!

**Comment by osdiab** [comment]
@jhuckaby np :) My first Flash PR, and hopefully one of my last hahah.

**Comment by osdiab** [comment]
@borisreitman i'll check that out for sure! Because I'm not going to actually pay for adobe animate.... lol

**Comment by borisreitman** [comment]
I applied the patch and it works for me. Going to use it.
