### ISSUE TITLE
'width' should probably not be assigned to 'height' 

### ISSUE THREAD

**Issue by almirus** [jhuckaby/webcamjs#227]
// switch width height if orientation needed
			if (orientation < 5) {
				canvas.width = img.width;
				canvas.height = img.height;
			} else {
				canvas.width = img.height;
				canvas.height = img.width;
			}

**Comment by jhuckaby** [comment]
@zsalab Any thoughts on this issue?  This is in your code and I honestly don't understand it.

**Comment by zsalab** [comment]
I don't understand the issue, can you be more precise? Whats wrong whit it? How can I reproduce?
This code is because of the iOS device can be turned and based on the exif data we must swap the orientation (the device never change the image aspect based on the orientation, just save the orientation as exif data, we must do this to get the proper image for any orientation).
