### ISSUE TITLE
Unable to save image via php.

### ISSUE THREAD

**Issue by weasy** [jhuckaby/webcamjs#75]
So I am new to coding in general, though I have been a linux admin for a long while. 
 I loved this bit of code. I thought this would be a fun project to start out with. 
I can't get it to upload via php, here is the sections that include the form, take snapshot function
In a php file, I added the javascript below with a few lines of php at the bottom. 

Could you tell me what I'm doing wrong with your script? 

	<form>
		<input type=button value="Take Snapshot" onClick="take_snapshot()">
	</form>
	

	
		
	<form>
		<input type=button value="Take Snapshot" onClick="take_snapshot()">
	</form>
	

	
	
	<script language="JavaScript">
		function take_snapshot() {
			// take snapshot and get image data
			Webcam.snap( function(data_uri) {
				// display results in page
				document.getElementById('results').innerHTML = 
					'<h2>Here is your image:</h2>' + 
					'<img src="'+data_uri+'"/>';
			} );
		}
	</script>
		<form>
		<input type=button value="upload" onClick="Webcam.upload()">
	</form>
	<script language="JavaScript">
		 Webcam.snap( function(data_uri) {
		        // snap complete, image data is in 'data_uri'

		       Webcam.upload( data_uri, 'snap.php', function(code, text) {
		            // Upload complete!
		            // 'code' will be the HTTP response code from the server, e.g. 200
		            // 'text' will be the raw response content
		       } );

		   } );
	</script>
<?php
move_uploaded_file($_FILES['webcam']['tmp_name'], 'webcam.jpg') || die;

echo "success";

?>

**Comment by jhuckaby** [comment]
Please note that this is a place to report bugs in the library.  In general we cannot give programming help.  You should try /r/javascript or /r/webdev on Reddit, or StackOverflow.  That being said, I will try to help really quick:

Your HTML page seems to be trying to do two different things at the same time.  It appears that you just copied & pasted pieces of code from the demo test page and the docs and expected them to work together.  Your page is trying to take a snapshot and show it to the user (like the demo test page does), but it's also trying to take a snapshot on page load (before the webcam is even ready) and upload it.  This won't work as is, because the camera isn't ready when the page first loads.

I suggest you remove all the JavaScript code and start fresh.  You want everything to be inside the `take_snapshot()` function, not outside of it.  I recommend something like this:

```html
<form>
    <input type=button value="Take Snapshot" onClick="take_snapshot()">
</form>
```

And then:

```javascript
<script language="JavaScript">
function take_snapshot() {
   Webcam.snap( function(data_uri) {
            // snap complete, image data is in 'data_uri'
           Webcam.upload( data_uri, 'snap.php', function(code, text) {
                // Upload complete!
                // 'code' will be the HTTP response code from the server, e.g. 200
                // 'text' will be the raw response content
                alert( "Upload complete: " + code + ": " + text );
           } );
       } );
}
</script>
```

Finally, please note that your PHP code is attempting to save the webcam snapshot in the CURRENT working directory where your PHP file is located.  It's trying to save out a file named "webcam.jpg".  I assume your web server will not allow this, unless you make specific permission changes to the directory or file.  chmod 777 or the like.

Good luck.
